### ISSUE TITLE
cellLatLon stale branch

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#177]
@tsccsj 

I am trying to clean up our repository of stale branches. Your commit e44388f09d0c39a5485894594b4c5e7cd66d6ba3 is at the head of a branch you haven't updated for a while. Can this be merged with master? You can view your commit history here:

https://github.com/TerraFusion/basicFusion/network

and scroll to the left.

**Comment by tsccsj** [comment]
Hi Landon,
This branch has a cellLatLon directory that doesn't exist in the master branch. It is not directly used by the BasicFusion code, but rather a place to develop the original cell lat-lon interpolation codes. @kyang2014 has already put the functions in either the master branch, or some prepossessing codes. 
So the "cellLatLon" is not directly a part of the basic fusion. But it is good that the codes are kept somewhere. (That's why we have the cellLatLon branch). 
Any suggestions to this?

**Comment by LandonTClipp** [comment]
Okay if you would like to keep this branch, that is fine. I'm not terribly obligated to remove it. Just doing a review of all branches and deleting what nobody is using anymore. Thanks.
