### ISSUE TITLE
CERES attributes

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#21]
The attributes for CERES have hard coded values. The program needs to be able to read the original attribute values and copy those over to the new HDF5 attributes.

**Comment by kyang2014** [comment]
Some attribute values need to be corrected. Some attributes need to be removed.
1) The units for ""Colatitude_of_CERES_FOV_at_TOA" should be degrees_east.
2) The units for "Longitude ......" should be degrees_north.
3) Attribute coordsys, format should be removed. 

4) Questions for "valid_range" attributes, where do you get these values? 
I see in the code:
 status = CERESinsertAttrs( SWFilteredDatasetID, "CERES SW Filtered Radiance, Upwards", "Watts per square meter per steradian", -10.0f, 510.0f );

valid_range=(-10,510)
They are still hard-coded. If you get these values from the product document, you should cite the URL of  the document. Otherwise, these numbers look  suspicious too me.

**Comment by kyang2014** [comment]
Also see the following obvious mistake in the code:
status = CERESinsertAttrs( colatitudeDatasetID, "CERES SW Filtered Radiance, Upwards", "deg", 0.0f, 180.0f );

The long name should be "Colatitude of CERES FOV at TOA".  
Should be corrected.

**Comment by kyang2014** [comment]
I rewrote the ceres attribute handling routines. This issue is resolved.
