### ISSUE TITLE
Handle missing files

### ISSUE THREAD

**Issue by LandonTClipp** [TerraFusion/basicFusion#57]
Sometimes an instrument will not be included in the inputFiles.txt file due to the file not being available (not problem with software, file literally does not exist). Need put some kind of marker in the input file that fusion program should not expect to see a certain granule. Otherwise, program would crash if it is expecting a granule and it does not see it in the input file.

**Comment by LandonTClipp** [comment]
@davidraila 
This will need to be something your DB script handles. All it will need to do is to place the string marker "[instrument name] DATA N/A" if there is no data for a certain instrument in the orbit. For instance, if there is no data for CERES, between the MOPITT and MODIS file listings, you should write "CERES DATA N/A". Perhaps it is obvious, but there should be no CERES files if the CERES DATA N/A flag is present in the file.

**Comment by LandonTClipp** [comment]
@kyang2014 @ldigirol 

I know this was discussed in the meeting, but are you certain we should not put any marker in the fusion file indicating that data for a certain file is not available? Indicating such a thing could even be as simple as including the inputFiles.txt somewhere in the fusion file, I don't think it'd hurt. Up to you two (and Dr. Zhao) however.

**Comment by kyang2014** [comment]
Landon,
It is not the data that is not present in the certain file. It is that we miss certain granules which are supposed to be there. The reason for that is that the original granule is not provided by the original data distributor. We DEFINITELY should mark that that granule is missing because that the original granule is not there. How to mark that? I prefer to put an attribute in the fusion file and this seems the consensus from the meeting.

For MODIS night time visible band data, we don’t include those radiance values according to the User’s guide. We should definitely include this in our user document but not in the fusion file since this is a rule rather than an unexpected input from the original data distributor.

Kent

**Comment by LandonTClipp** [comment]
You are correct, poor choice of wording on my part. The granule itself is not present, not just some data (with exception of MODIS as you said). I'll wait for input from Dr. Di Girolamo and Dr. Zhao unless you have an idea of where you want the attribute to go/if we can go ahead and write code to mark the granule as missing.

**Comment by LandonTClipp** [comment]
David will not need to worry about this, the label handling for non-existent files will be handled by whatever script queries his database. I can work on this.
