### ISSUE TITLE
MODIS, MISR and ASTER special values and units

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#83]
Need to check if we need to provide attributes to provide special value information(-991 to -998 for MODIS for example).

Also Guangyu will provide units for radiance fields. They are missing from the original fields.

**Comment by kyang2014** [comment]
Both ASTER and MISR radiance data, which are converted from DN,  have the same unit as MODIS, namely, W m^-2 sr^-1 um ^-1, or Watts/m^2/micrometer/steradian.

**Comment by kyang2014** [comment]
We need to use the following units "Watts/m^2/micrometer/steradian" for ASTER and MISR radiance fields. Also check CERES and MOPITT.

**Comment by LandonTClipp** [comment]
I have added units as specified for ASTER and MISR. To my knowledge, CERES and MOPITT are not unpacked so no physical units are available.

**Comment by LandonTClipp** [comment]
Asked Guangyu about units for MOPITT. CERES code currently just copies all attributes from HDF4 to HDF5. May be an issue because CERES units is "Watts per meter squared per micrometer per steradian" instead of "Watts/m^2/micrometer/steradian". They are the same units but don't know if we want the same lexical format for all units. If we do, need to change CERES copying the attributes.
